INSERT INTO auth.role_permissions(role_id, permission_id)
SELECT
    r.id,
    p.id
FROM auth.roles AS r
JOIN auth.permissions AS p
ON p.slug IN (
    'TENANT.CREATE',
    'TENANT.READ',
    'TENANT.UPDATE',

    'ECOSYSTEM.CREATE',
    'ECOSYSTEM.READ',
    'ECOSYSTEM.UPDATE',
    'ECOSYSTEM.DELETE',

    'TENANTPLAN.CREATE',
    'TENANTPLAN.READ',
    'TENANTPLAN.UPDATE',

    'TENANTDOMAIN.CREATE',
    'TENANTDOMAIN.READ',
    'TENANTDOMAIN.UPDATE',
    'TENANTDOMAIN.DELETE',

    'WIDGET.CREATE',
    'WIDGET.READ',
    'WIDGET.UPDATE',
    'WIDGET.DELETE',

    'WIDGETORIGIN.CREATE',
    'WIDGETORIGIN.READ',
    'WIDGETORIGIN.UPDATE',
    'WIDGETORIGIN.DELETE',

    'NOTIFICATIONCHANNEL.READ',
    'NOTIFICATIONCHANNEL.UPDATE',

    'NOTIFICATIONTEMPLATE.CREATE',
    'NOTIFICATIONTEMPLATE.READ',
    'NOTIFICATIONTEMPLATE.UPDATE',
    'NOTIFICATIONTEMPLATE.DELETE',

    'NOTIFICATION.READ',

    'NOTIFICATIONQUEUE.READ',

    'NOTIFICATIONDELIVERY.READ',

    'ORGANIZATION.CREATE',
    'ORGANIZATION.READ',
    'ORGANIZATION.UPDATE',

    'PROFILE.READ',

    'MEMBERSHIP.READ',

    'MEMBERSHIPROLE.READ',

    'SERVICE.READ',

    'SCHEDULE.READ',

    'AVAILABILITY.READ',

    'BOOKINGPOLICY.READ',

    'BOOKING.READ',

    'ATTENDEE.READ',

    'OUTOFOFFICE.READ',

    'DESTINATIONCALENDAR.READ',

    'DESTINATIONSHEETS.READ',

    'RESOURCETYPE.READ',

    'RESOURCE.READ',

    'RESOURCEPRICING.READ',

    'RESOURCEASSIGNMENT.READ',

    'RESOURCECALENDAR.READ',

    'RESOURCEMAINTENANCE.READ',

    'RESOURCEATTRIBUTE.READ',

    'RESOURCEOVERRIDE.READ',

    'CUSTOMER.READ',

    'CUSTOMERNOTE.READ',

    'CUSTOMERACTIVITY.READ',

    'CUSTOMERTAG.READ',

    'CUSTOMERSOURCE.READ',

    'NOTIFICATIONPREFERENCE.READ',

    'USER.READ',

    'ACCOUNT.READ',

    'APIKEY.READ',

    'SESSION.READ',

    'REFRESHTOKEN.READ',

    'AUDITACTOR.READ',

    'AUDITEVENT.READ',

    'AUDITRESOURCE.READ',

    'AUDITCHANGE.READ'
)
WHERE r.name = 'PLATFORM_MANAGER';
