INSERT INTO auth.role_permissions(role_id, permission_id)
SELECT
    r.id,
    p.id
FROM auth.roles AS r
JOIN auth.permissions AS p
ON p.slug IN (
    'ORGANIZATION.CREATE',
    'ORGANIZATION.READ',
    'ORGANIZATION.UPDATE',
    'ORGANIZATION.DELETE',

    'PROFILE.CREATE',
    'PROFILE.READ',
    'PROFILE.UPDATE',
    'PROFILE.DELETE',

    'MEMBERSHIP.CREATE',
    'MEMBERSHIP.READ',
    'MEMBERSHIP.UPDATE',
    'MEMBERSHIP.DELETE',

    'MEMBERSHIPROLE.CREATE',
    'MEMBERSHIPROLE.READ',
    'MEMBERSHIPROLE.DELETE',
    'MEMBERSHIPROLE.ASSIGN',
    'MEMBERSHIPROLE.REVOKE',

    'SERVICE.CREATE',
    'SERVICE.READ',
    'SERVICE.UPDATE',
    'SERVICE.DELETE',

    'SCHEDULE.CREATE',
    'SCHEDULE.READ',
    'SCHEDULE.UPDATE',
    'SCHEDULE.DELETE',

    'AVAILABILITY.CREATE',
    'AVAILABILITY.READ',
    'AVAILABILITY.UPDATE',
    'AVAILABILITY.DELETE',

    'BOOKINGPOLICY.CREATE',
    'BOOKINGPOLICY.READ',
    'BOOKINGPOLICY.UPDATE',
    'BOOKINGPOLICY.DELETE',

    'BOOKING.CREATE',
    'BOOKING.READ',
    'BOOKING.UPDATE',
    'BOOKING.DELETE',
    'BOOKING.CANCEL',
    'BOOKING.REJECT',

    'ATTENDEE.CREATE',
    'ATTENDEE.READ',
    'ATTENDEE.UPDATE',
    'ATTENDEE.DELETE',

    'OUTOFOFFICE.CREATE',
    'OUTOFOFFICE.READ',
    'OUTOFOFFICE.UPDATE',
    'OUTOFOFFICE.DELETE',

    'DESTINATIONCALENDAR.CREATE',
    'DESTINATIONCALENDAR.READ',
    'DESTINATIONCALENDAR.UPDATE',
    'DESTINATIONCALENDAR.DELETE',

    'DESTINATIONSHEETS.CREATE',
    'DESTINATIONSHEETS.READ',
    'DESTINATIONSHEETS.UPDATE',
    'DESTINATIONSHEETS.DELETE',

    'RESOURCETYPE.CREATE',
    'RESOURCETYPE.READ',
    'RESOURCETYPE.UPDATE',
    'RESOURCETYPE.DELETE',

    'RESOURCE.CREATE',
    'RESOURCE.READ',
    'RESOURCE.UPDATE',
    'RESOURCE.DELETE',

    'RESOURCEPRICING.CREATE',
    'RESOURCEPRICING.READ',
    'RESOURCEPRICING.UPDATE',
    'RESOURCEPRICING.DELETE',

    'RESOURCEASSIGNMENT.CREATE',
    'RESOURCEASSIGNMENT.READ',
    'RESOURCEASSIGNMENT.UPDATE',
    'RESOURCEASSIGNMENT.DELETE',

    'RESOURCECALENDAR.CREATE',
    'RESOURCECALENDAR.READ',
    'RESOURCECALENDAR.UPDATE',
    'RESOURCECALENDAR.DELETE',

    'RESOURCEMAINTENANCE.CREATE',
    'RESOURCEMAINTENANCE.READ',
    'RESOURCEMAINTENANCE.UPDATE',
    'RESOURCEMAINTENANCE.DELETE',

    'RESOURCEATTRIBUTE.CREATE',
    'RESOURCEATTRIBUTE.READ',
    'RESOURCEATTRIBUTE.UPDATE',
    'RESOURCEATTRIBUTE.DELETE',

    'RESOURCEOVERRIDE.CREATE',
    'RESOURCEOVERRIDE.READ',
    'RESOURCEOVERRIDE.UPDATE',
    'RESOURCEOVERRIDE.DELETE',

    'CUSTOMER.CREATE',
    'CUSTOMER.READ',
    'CUSTOMER.UPDATE',
    'CUSTOMER.DELETE',

    'CUSTOMERNOTE.CREATE',
    'CUSTOMERNOTE.READ',
    'CUSTOMERNOTE.UPDATE',
    'CUSTOMERNOTE.DELETE',

    'CUSTOMERACTIVITY.CREATE',
    'CUSTOMERACTIVITY.READ',
    'CUSTOMERACTIVITY.UPDATE',
    'CUSTOMERACTIVITY.DELETE',

    'CUSTOMERTAG.CREATE',
    'CUSTOMERTAG.READ',
    'CUSTOMERTAG.UPDATE',
    'CUSTOMERTAG.DELETE',

    'CUSTOMERSOURCE.CREATE',
    'CUSTOMERSOURCE.READ',
    'CUSTOMERSOURCE.UPDATE',
    'CUSTOMERSOURCE.DELETE',

    'NOTIFICATIONPREFERENCE.CREATE',
    'NOTIFICATIONPREFERENCE.READ',
    'NOTIFICATIONPREFERENCE.UPDATE',
    'NOTIFICATIONPREFERENCE.DELETE'
)
WHERE r.name = 'ORGANIZATION_OWNER';
