INSERT INTO auth.role_permissions(role_id, permission_id)
SELECT
    r.id,
    p.id
FROM auth.roles AS r
JOIN auth.permissions AS p
ON p.slug IN (
    'ORGANIZATION.READ',

    'PROFILE.READ',
    'PROFILE.UPDATE',

    'MEMBERSHIP.READ',

    'MEMBERSHIPROLE.READ',

    'SERVICE.READ',

    'SCHEDULE.READ',

    'AVAILABILITY.READ',
    'AVAILABILITY.UPDATE',

    'BOOKINGPOLICY.READ',

    'BOOKING.CREATE',
    'BOOKING.READ',
    'BOOKING.UPDATE',
    'BOOKING.CANCEL',

    'ATTENDEE.CREATE',
    'ATTENDEE.READ',
    'ATTENDEE.UPDATE',

    'OUTOFOFFICE.CREATE',
    'OUTOFOFFICE.READ',
    'OUTOFOFFICE.UPDATE',
    'OUTOFOFFICE.DELETE',

    'DESTINATIONCALENDAR.READ',

    'DESTINATIONSHEETS.READ',

    'RESOURCETYPE.READ',

    'RESOURCE.READ',

    'RESOURCEPRICING.READ',

    'RESOURCEASSIGNMENT.CREATE',
    'RESOURCEASSIGNMENT.READ',
    'RESOURCEASSIGNMENT.UPDATE',

    'RESOURCECALENDAR.READ',

    'RESOURCEMAINTENANCE.READ',

    'RESOURCEATTRIBUTE.READ',

    'RESOURCEOVERRIDE.READ',

    'CUSTOMER.CREATE',
    'CUSTOMER.READ',
    'CUSTOMER.UPDATE',

    'CUSTOMERNOTE.CREATE',
    'CUSTOMERNOTE.READ',
    'CUSTOMERNOTE.UPDATE',

    'CUSTOMERACTIVITY.CREATE',
    'CUSTOMERACTIVITY.READ',

    'CUSTOMERTAG.CREATE',
    'CUSTOMERTAG.READ',

    'CUSTOMERSOURCE.READ',

    'NOTIFICATIONPREFERENCE.READ',
    'NOTIFICATIONPREFERENCE.UPDATE'
)
WHERE r.name = 'STAFF';
